name: itr_env
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python==3.9
  - ca-certificates # ==2021.10.8
  - certifi # ==2021.10.8
  - et_xmlfile # ==1.1.0
  - ipython==8.1.1
  - jupyterlab==3.3.0
  # - matplotlib==3.5.1
  # - numpy==1.22.2
  # - openpyxl # ==3.0.9
  # - openscm-units # ==0.5.0
  - openssl # ==1.1.1l
  # - pandas==1.4.1
  # - pint==0.18
  # - pint-pandas==0.2
  # - pydantic==1.8.2
  - pytz # ==2021.3
  - setuptools==60.9.3
  # - sqlite==3.37.0
  - wheel>=0.36.2
  - pip:
    - -r requirements.txt
