name: itr_getting_started
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.13
  - pip=22.1.2
  - pip:
    # While ITR is not available on PyPI, or if environment is used for development purposes, comment out line 11, else
    # comment out line 12 & 13.
    # - ITR
    - -r ../requirements.txt
    - -e ../.
