---
name: "🧪 Linting checks"

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      [opened, reopened, edited]

jobs:
  lint:
    name: "Check repository content"
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Checking YAML files (yamllint)"
        continue-on-error: true
        run: |
          pip install yamllint
          yamllint .

      - name: "Checking TOML files (gh-action-toml-linter)"
        continue-on-error: true
        uses: yisonPylkita/gh-action-toml-linter@0.1.3

      - name: "Checking GitHub Actions (actionlint)"
        continue-on-error: true
        id: actionlint
        uses: raven-actions/actionlint@v1
        with:
          matcher: true  # optional
          cache: true  # optional
          fail-on-error: true  # optional
          files: ".github/workflows/*.yaml, .github/workflows/*.yml"
          # flags: "-ignore SC2086"  # optional

      - name: "Problem report (conditional step)"
        if: ${{ steps.actionlint.outputs.exit-code != 0 }}
        # yamllint disable rule:line-length
        run: |
          echo "Used actionlint version ${{ steps.actionlint.outputs.version-semver }}"
          echo "Used actionlint release ${{ steps.actionlint.outputs.version-tag }}"
          echo "actionlint ended with ${{ steps.actionlint.outputs.exit-code }} exit code"
          echo "actionlint ended because '${{ steps.actionlint.outputs.exit-message }}'"
          echo "actionlint found ${{ steps.actionlint.outputs.total-errors }} errors"
          echo "actionlint checked ${{ steps.actionlint.outputs.total-files }} files"
          echo "actionlint cache used: ${{ steps.actionlint.outputs.cache-hit }}"
