---
name: "🧪 Unit tests"

on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      [opened, reopened, edited]

jobs:
  build:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:

      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Setup PDM for build commands"
        uses: pdm-project/setup-pdm@v3

      - name: "Setup Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pdm lock
          pdm export -o requirements.txt
          pip install -r requirements.txt
          pip install .

      - name: "Run unit tests: pytest"
        run: python -m pytest test
